services:
  app:
    build: .
    container_name: node_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"          # Expose the app on port 3000
    command: yarn dev:start        # Use nodemon to start the app in development mode
    environment:
      - NODE_ENV=development

  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: my_interview_password
  #     MYSQL_DATABASE: my_interview_database
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

# volumes:
#   db_data:
