services:
  app:
    build: .
    container_name: node_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    command: sh -c "npm run dev:migrate && npm run dev:seed && npm run dev:start"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my_interview_password
      - DB_NAME=my_interview_database
      - DB_DIALECT = mysql
      - DB_PORT=3306
      - SERVER_URL=http://localhost:8080/
      - JSON_LIMIT=50mb
      - URL_ENCODED_LIMIT=50mb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my_interview_password
      MYSQL_DATABASE: my_interview_database
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
